version: "3"

services:

  # Database
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  # Database web-view
  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  # Backend
  node-app:
    container_name: Backend
    build:
      context: ./Backend
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      REACT_APP_DB_URI: "mongodb://admin:password@mongodb:27017"
      REACT_APP_PORT: 8004

  # Frontend
  react-app:
    container_name: Frontend
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - node-app
  
  # Email send api
  email-api:
    container_name: EmailAPI
    build:
      context: ./EmailAPI
      dockerfile: Dockerfile
    ports:
      - "8003:8003"

volumes:
  mongodb-data:
