version: "3"

services:
  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb-data:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

  mongo-express:
    image: mongo-express
    container_name: mongo-express
    ports:
      - "8081:8081"
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: admin
      ME_CONFIG_MONGODB_ADMINPASSWORD: password
      ME_CONFIG_MONGODB_SERVER: mongodb
    depends_on:
      - mongodb

  node-app:
    container_name: Backend
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8004:8004"
    environment:
      REACT_APP_DB_URI: "mongodb://admin:password@mongodb:27017"
      REACT_APP_PORT: 8004

  # React application container
  react-app:
    container_name: Frontend
    build: ./Capstone # Update this path accordingly
    image: frontend # Update this file name accordingly
    ports:
      - "3000:3000"
    depends_on:
      - node-app

volumes:
  mongodb-data:
